PEP_ROLES: frozenset[str] = frozenset({
    "diputado",
    "diputada",
    "senador",
    "senadora",
    "concejal",
    "concejala",
    "intendente",
    "intendenta",
    "gobernador",
    "gobernadora",
    "presidente",
    "presidenta",
    "ministro",
    "ministra",
    "secretario",
    "secretaria",
    "legislador",
    "legisladora",
    "jefe de gobierno",
    "jefa de gobierno",
})
